name: Linux

# Qt官方没有linux平台的x86包
on: 
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-18.04,ubuntu-20.04]
        # qt_ver: [5.9.9,5.12.10,5.15.2]
        
        os: [ubuntu-22.04]
        qt_ver: [5.15.2]
        
        qt_arch: [gcc_64]
        
    env:
        targetName: Xplist
        VERSION: Linux
              
    steps:
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3.3.0
        with:
          version: ${{ matrix.qt_ver }}
          cache: false
      
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev libxcb*
                   
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          qmake
          make
          
      - name: Install FUSE (for AppImage)
        run: sudo apt-get update && sudo apt-get install -y fuse libfuse2
      
      - name: install linuxdeployqt 
        run: |
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage            
          
      # 打包
      - name: package
        run: |
         cp icon.png bin/release/icon.png
         cp default.desktop bin/release/default.desktop
         cp plistutil-x86_64.AppImage bin/release/plistutil-x86_64.AppImage
         chmod +x bin/release/plistutil-x86_64.AppImage
         export VERSION # linuxdeployqt uses this for naming the file
         ./linuxdeployqt-continuous-x86_64.AppImage bin/release/${targetName} -unsupported-allow-new-glibc -appimage
          
      # 上传artifacts          
      - uses: actions/upload-artifact@v4
        with:
          # name: ${{ env.targetName }}-${{ matrix.os }}-${{ matrix.qt_ver }}-${{ env.VERSION }}-x86_64.AppImage
          name: ${{ env.targetName }}-${{ env.VERSION }}-x86_64.AppImage
          path: ${{ env.targetName }}-${{ env.VERSION }}-x86_64.AppImage
          
      # tag 上传Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.targetName }}-${{ env.VERSION }}-x86_64.AppImage
          
          # asset_name: ${{ env.targetName }}-${{ matrix.os }}-${{ matrix.qt_ver }}-${{ env.VERSION }}-x86_64.AppImage
          asset_name: ${{ env.targetName }}-${{ env.VERSION }}-x86_64.AppImage
          
          tag: ${{ github.ref }}
          overwrite: true         
          
          
    
